/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package otb;

import java.awt.GridLayout;
import java.awt.PopupMenu;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javafx.util.converter.DateStringConverter;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DateFormatter;
import org.jdesktop.swingx.JXDatePicker;

/**
 *
 * @author Shubhashis
 */
public class AdminPanel extends javax.swing.JFrame {
    
    JXDatePicker picker = new JXDatePicker();
    String dateString;
    boolean flg[];
    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents();
        setLocationRelativeTo(this);
        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();
        
        flg = new boolean[8];
        for(int i=0;i<8;i++)
        {
            flg[i]=false;
        }
        
        jPanel2.add(jPanel4);
        jPanel2.repaint();
        jPanel2.revalidate();
        
        picker.setDate(Calendar.getInstance().getTime());
        picker.setFormats(new SimpleDateFormat("dd.MM.yyyy"));
        jPanel6.setLayout(new GridLayout(1, 1));
        jPanel6.add(picker);
        jPanel6.repaint();
        jPanel6.revalidate();
        
        picker.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date datePick = picker.getDate();
                SimpleDateFormat sm = new SimpleDateFormat("E dd.MM.yyyy");
                dateString = sm.format(datePick);
                System.err.println(dateString);
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        AdminAddBus = new javax.swing.JButton();
        AdminRemove = new javax.swing.JButton();
        AdminApprove = new javax.swing.JButton();
        AdminLogOut = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        MasterPanel = new javax.swing.JPanel();
        AddBusPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        AdminAddPickUp1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        AdminAddTo1 = new javax.swing.JTextField();
        AdminAddBusText1 = new javax.swing.JTextField();
        AdminAddFrom1 = new javax.swing.JTextField();
        AdminAddTime = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RemovePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ApprovePanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Copy = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(Toolkit.getDefaultToolkit().getImage(JFrame.class.getResource("/otb/seat/icon.jpg")));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(21, 21, 21));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel2MouseExited(evt);
            }
        });
        jPanel2.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(21, 21, 21));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
        });

        AdminAddBus.setBackground(new java.awt.Color(21, 21, 21));
        AdminAddBus.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        AdminAddBus.setForeground(new java.awt.Color(255, 255, 255));
        AdminAddBus.setText("Add Bus");
        AdminAddBus.setBorder(null);
        AdminAddBus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AdminAddBusMouseExited(evt);
            }
        });
        AdminAddBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminAddBusActionPerformed(evt);
            }
        });

        AdminRemove.setBackground(new java.awt.Color(21, 21, 21));
        AdminRemove.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        AdminRemove.setForeground(new java.awt.Color(255, 255, 255));
        AdminRemove.setText("Remove");
        AdminRemove.setBorder(null);
        AdminRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AdminRemoveMouseExited(evt);
            }
        });
        AdminRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminRemoveActionPerformed(evt);
            }
        });

        AdminApprove.setBackground(new java.awt.Color(21, 21, 21));
        AdminApprove.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        AdminApprove.setForeground(new java.awt.Color(255, 255, 255));
        AdminApprove.setText("Approve");
        AdminApprove.setBorder(null);
        AdminApprove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AdminApproveMouseExited(evt);
            }
        });
        AdminApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminApproveActionPerformed(evt);
            }
        });

        AdminLogOut.setBackground(new java.awt.Color(21, 21, 21));
        AdminLogOut.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        AdminLogOut.setForeground(new java.awt.Color(255, 255, 255));
        AdminLogOut.setText("LOG OUT");
        AdminLogOut.setBorder(null);
        AdminLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AdminLogOutMouseExited(evt);
            }
        });
        AdminLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminAddBus, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AdminRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AdminApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AdminLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(AdminAddBus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(AdminRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(AdminApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(AdminLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 178, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, "card2");

        jPanel4.setBackground(new java.awt.Color(229, 192, 134));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 123, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, "card2");

        MasterPanel.setLayout(new java.awt.CardLayout());

        AddBusPanel.setBackground(new java.awt.Color(229, 192, 134));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("From:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Pick up Place:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("To:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Bus:");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Date:");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Time:");

        jButton2.setBackground(new java.awt.Color(229, 192, 134));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otb/seat/submit.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Rockwell", 2, 20)); // NOI18N
        jLabel1.setText("Add Bus");

        javax.swing.GroupLayout AddBusPanelLayout = new javax.swing.GroupLayout(AddBusPanel);
        AddBusPanel.setLayout(AddBusPanelLayout);
        AddBusPanelLayout.setHorizontalGroup(
            AddBusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddBusPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(AddBusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(AddBusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminAddFrom1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminAddTo1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminAddPickUp1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AddBusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(AdminAddTime, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AdminAddBusText1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        AddBusPanelLayout.setVerticalGroup(
            AddBusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddBusPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(AddBusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(AdminAddFrom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddBusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(AdminAddPickUp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddBusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(AdminAddTo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddBusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(AdminAddBusText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddBusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddBusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(AdminAddTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        MasterPanel.add(AddBusPanel, "card2");

        RemovePanel.setBackground(new java.awt.Color(229, 192, 134));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bus ID", "From", "To", "Bus", "Date", "Time"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setText("Bus ID:");

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(229, 192, 134));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otb/seat/remove.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Rockwell", 2, 18)); // NOI18N
        jLabel4.setText("Bus Information");

        javax.swing.GroupLayout RemovePanelLayout = new javax.swing.GroupLayout(RemovePanel);
        RemovePanel.setLayout(RemovePanelLayout);
        RemovePanelLayout.setHorizontalGroup(
            RemovePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RemovePanelLayout.createSequentialGroup()
                .addGroup(RemovePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RemovePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RemovePanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel2)
                        .addGap(36, 36, 36)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RemovePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        RemovePanelLayout.setVerticalGroup(
            RemovePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RemovePanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(RemovePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        MasterPanel.add(RemovePanel, "card2");

        ApprovePanel.setBackground(new java.awt.Color(229, 192, 134));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "User Name", "Status", "bKash ID"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setText("ID:");

        jComboBox2.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT" }));
        jComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox2MouseClicked(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(229, 192, 134));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otb/seat/approve.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Rockwell", 2, 18)); // NOI18N
        jLabel5.setText("Client Information");

        javax.swing.GroupLayout ApprovePanelLayout = new javax.swing.GroupLayout(ApprovePanel);
        ApprovePanel.setLayout(ApprovePanelLayout);
        ApprovePanelLayout.setHorizontalGroup(
            ApprovePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ApprovePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ApprovePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addGroup(ApprovePanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        ApprovePanelLayout.setVerticalGroup(
            ApprovePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ApprovePanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(ApprovePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ApprovePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        MasterPanel.add(ApprovePanel, "card2");

        javax.swing.GroupLayout CopyLayout = new javax.swing.GroupLayout(Copy);
        Copy.setLayout(CopyLayout);
        CopyLayout.setHorizontalGroup(
            CopyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        CopyLayout.setVerticalGroup(
            CopyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );

        MasterPanel.add(Copy, "card2");

        jMenu1.setText("File");

        jCheckBoxMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Exit");
        jMenu1.add(jCheckBoxMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(MasterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(MasterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdminAddBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminAddBusActionPerformed
        // TODO add your handling code here:
        clearFlag();
        flg[0]=true;
        AdminAddBus.setBackground(new java.awt.Color(122,122,122));
        
        System.err.println("asce");
        MasterPanel.removeAll();
        MasterPanel.repaint();
        MasterPanel.revalidate();
        
        MasterPanel.add(AddBusPanel);
        MasterPanel.repaint();
        MasterPanel.revalidate();
        
        
    }//GEN-LAST:event_AdminAddBusActionPerformed

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseEntered

    private void jPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPanel2MouseExited

    private void AdminApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminApproveActionPerformed
        // TODO add your handling code here:
        clearFlag();
        flg[2]=true;
        AdminApprove.setBackground(new java.awt.Color(122,122,122));
        
        MasterPanel.removeAll();
        MasterPanel.repaint();
        MasterPanel.revalidate();
        
        MasterPanel.add(ApprovePanel);
        MasterPanel.repaint();
        MasterPanel.revalidate();
        
        DefaultTableModel dm = (DefaultTableModel) jTable2.getModel();
        int rowCount = dm.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            dm.removeRow(i);
        }
        
        String sql = "select * from purchase where bkash != 0 and status !=1";
        ArrayList purchaseIdArrayList = DatabaseHelper.fetchData(sql, "p_id");
        ArrayList usernameArrayList = DatabaseHelper.fetchData(sql, "username");
        ArrayList statusArrayList = DatabaseHelper.fetchData(sql, "status");
        ArrayList bKashArrayList = DatabaseHelper.fetchData(sql, "bkash");
        
        for(int i=0;i<purchaseIdArrayList.size();i++)
        {
            Object[] row = { purchaseIdArrayList.get(i), usernameArrayList.get(i), statusArrayList.get(i), bKashArrayList.get(i)};
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            model.addRow(row);
        }
    }//GEN-LAST:event_AdminApproveActionPerformed

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        // TODO add your handling code here:
        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();
        
        jPanel2.add(jPanel1);
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
        // TODO add your handling code here:
        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();
        
        jPanel2.add(jPanel4);
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_jPanel4MouseExited

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
        // TODO add your handling code here:
        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();
        
        jPanel2.add(jPanel4);
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_jPanel1MouseExited

    private void AdminAddBusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminAddBusMouseExited
        // TODO add your handling code here:
        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();
        
        jPanel2.add(jPanel4);
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_AdminAddBusMouseExited

    private void AdminRemoveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminRemoveMouseExited
        // TODO add your handling code here:
        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();
        
        jPanel2.add(jPanel4);
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_AdminRemoveMouseExited

    private void AdminApproveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminApproveMouseExited
        // TODO add your handling code here:
        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();
        
        jPanel2.add(jPanel4);
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_AdminApproveMouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String fromm,pickUpPlace , too , bus , time;
        
        
        
        fromm = AdminAddFrom1.getText();
        pickUpPlace = AdminAddPickUp1.getText();
        too = AdminAddTo1.getText();
        bus = AdminAddBusText1.getText();
        time = AdminAddTime.getText();
        
        if(fromm.length()==0 || pickUpPlace.length()==0 || too.length()==0 || bus.length()==0 || dateString.length()==0 || time.length()==0)
        {
            JOptionPane.showMessageDialog(this, "Correct your Input","Wrong Entry !!",JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            String sql = "insert into booking (fromm,too,bus,date,time) values ( '"+fromm+"' , '"+too+"' , '"+bus+"' , '"+dateString+"' , '"+time+"')";
            String pick_up = "insert into pickup values (null , '"+fromm+"' , '"+pickUpPlace+"' )";
            if(DatabaseHelper.insert(sql) && DatabaseHelper.insert(pick_up))
            {
                JOptionPane.showMessageDialog(this, "Data Entered","Correct Entry",JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Check Internet Connection","Warning",JOptionPane.INFORMATION_MESSAGE);
            }
            AdminAddFrom1.setText("");
            AdminAddPickUp1.setText("");
            AdminAddTo1.setText("");
            AdminAddBusText1.setText("");
            AdminAddTime.setText("");
            AdminAddPickUp1.setText("");
        }
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void AdminLogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminLogOutMouseExited
        // TODO add your handling code here:
        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();
        
        jPanel2.add(jPanel4);
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_AdminLogOutMouseExited

    private void AdminLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminLogOutActionPerformed
        // TODO add your handling code here:
        clearFlag();
        flg[3]=true;
        AdminLogOut.setBackground(new java.awt.Color(122,122,122));
        
        LogInRegister ob = new LogInRegister();
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AdminLogOutActionPerformed

    private void AdminRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminRemoveActionPerformed
        // TODO add your handling code here:
        clearFlag();
        flg[1]=true;
        AdminRemove.setBackground(new java.awt.Color(122,122,122));
        
        MasterPanel.removeAll();
        MasterPanel.repaint();
        MasterPanel.revalidate();
        
        MasterPanel.add(RemovePanel);
        MasterPanel.repaint();
        MasterPanel.revalidate();
        
        DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
        int rowCount = dm.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            dm.removeRow(i);
        }
        
        String sql = "select * from booking";
        ArrayList busIdArrayList = DatabaseHelper.fetchData(sql, "ID");
        ArrayList fromArrayList = DatabaseHelper.fetchData(sql, "fromm");
        ArrayList toArrayList = DatabaseHelper.fetchData(sql, "too");
        ArrayList busArrayList = DatabaseHelper.fetchData(sql, "bus");
        ArrayList dateArrayList = DatabaseHelper.fetchData(sql, "date");
        ArrayList timeArrayList = DatabaseHelper.fetchData(sql, "time");
        
        for(int i=0;i<busIdArrayList.size();i++)
        {
            Object[] row = { busIdArrayList.get(i), fromArrayList.get(i), toArrayList.get(i), busArrayList.get(i),
                dateArrayList.get(i), timeArrayList.get(i)};
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.addRow(row);
        }
    }//GEN-LAST:event_AdminRemoveActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
        String sql = "select distinct id from booking";
        jComboBox1.removeAllItems();
        ArrayList arr = DatabaseHelper.fetchData(sql, "id");
        for(int i=0;i<arr.size();i++)
        {
            jComboBox1.addItem(arr.get(i));
        }
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String selected = String.valueOf(jComboBox1.getSelectedItem());
        String sql = "delete from booking where id = '"+selected+"'";
        if(DatabaseHelper.update(sql))
        {
            AdminRemoveActionPerformed(evt);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Check Internet Connection","Warning !!",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseClicked
        // TODO add your handling code here:
        String sql = "select distinct p_id from purchase where bKash != 0 and status!=1";
        jComboBox2.removeAllItems();
        ArrayList arr = DatabaseHelper.fetchData(sql, "p_id");
        for(int i=0;i<arr.size();i++)
        {
            jComboBox2.addItem(arr.get(i));
        }
    }//GEN-LAST:event_jComboBox2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String selected = String.valueOf(jComboBox2.getSelectedItem());
        String sql = "update purchase set status = 1 where p_id = '"+selected+"'";
        if(DatabaseHelper.update(sql))
        {
            sql = "select * from purchase where p_id = '"+selected+"'";
            ArrayList arr = DatabaseHelper.fetchData(sql, "seat");
            ArrayList seats = parseSeat((String) arr.get(0));
            arr = DatabaseHelper.fetchData(sql, "bus_id");
            sql = "update booking set ";
            boolean ok = false;
            for(int i=0;i<seats.size();i++)
            {
                //seatSet.remove(jeiSeatBadDibe.get(i));
                if(ok)
                {
                    sql+= ", `"+ seats.get(i) + "` = 1";
                }
                else
                {
                    sql += "`"+ seats.get(i) + "` = 1";
                    ok=true;
                }
            }
            sql+=" where id = '"+arr.get(0)+"'";
            DatabaseHelper.update(sql);
            AdminApproveActionPerformed(evt);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Check Internet Connection","Warning !!",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }
    
    public void clearFlag()
    {
        if(flg[0]==true)
        {
            AdminAddBus.setBackground(new java.awt.Color(21,21,21));
            flg[0]=false;
        }
        if(flg[1]==true)
        {
            AdminRemove.setBackground(new java.awt.Color(21,21,21));
            flg[1]=false;
        }
        if(flg[2]==true)
        {
            AdminApprove.setBackground(new java.awt.Color(21,21,21));
            flg[2]=false;
        }
        if(flg[3]==true)
        {
            AdminLogOut.setBackground(new java.awt.Color(21,21,21));
            flg[3]=false;
        }
    }
    
    private ArrayList parseSeat(String seats)
    {
        ArrayList resultArrayList = new ArrayList();
        String st="";
        for(int i=0;i<seats.length();i++)
        {
            if(seats.charAt(i)>='A' && seats.charAt(i)<='Z')
            {
                st+=seats.charAt(i);
            }
            else if(seats.charAt(i)>='1' && seats.charAt(i)<='9')
            {
                st+=seats.charAt(i);
            }
            else if(st.length()>0)
            {
                System.err.println(st);
                resultArrayList.add(st);
                st="";
            }
            if(i==seats.length()-1)
            {
                resultArrayList.add(st);
                st="";
            }
        }
        return resultArrayList;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddBusPanel;
    private javax.swing.JButton AdminAddBus;
    private javax.swing.JTextField AdminAddBusText1;
    private javax.swing.JTextField AdminAddFrom1;
    private javax.swing.JTextField AdminAddPickUp1;
    private javax.swing.JTextField AdminAddTime;
    private javax.swing.JTextField AdminAddTo1;
    private javax.swing.JButton AdminApprove;
    private javax.swing.JButton AdminLogOut;
    private javax.swing.JButton AdminRemove;
    private javax.swing.JPanel ApprovePanel;
    private javax.swing.JPanel Copy;
    private javax.swing.JPanel MasterPanel;
    private javax.swing.JPanel RemovePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
